name: Deploy Project
on: push # push event

jobs:
  test: # first job
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repo
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci # or npm install
      - name: Run tests
        run: npm test

  deploy: # second job
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repo
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci # or npm install
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."