name: Reusable deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        required: false
        default: dist
        type: string
    # secrets:
    #   some-secret:
    #     required: false
    outputs:
      result:
        description: The result of the deployment operatin
        value:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name: '${{ inputs.artifact-name }}'
      - name: List files
        run: ls
      - name: Output info
        run: echo "Deploying and uploading.."
      - name: Set result output
        run: echo "step-result=success" >> $GITHUB_OUTPUT
